export const BANK_CONSENT_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  REVOKED: 'REVOKED',
  EXPIRED: 'EXPIRED',
} as const;

export const BANK_TXN_DIRECTION = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT',
} as const;

export const LEDGER_ACCOUNT_TYPE = {
  ASSET: 'ASSET',
  LIABILITY: 'LIABILITY',
  EQUITY: 'EQUITY',
  REVENUE: 'REVENUE',
  EXPENSE: 'EXPENSE',
} as const;

export const JOURNAL_ENTRY_STATUS = {
  DRAFT: 'DRAFT',
  POSTED: 'POSTED',
  REVERSED: 'REVERSED',
} as const;

export const JOURNAL_SOURCE_TYPE = {
  BANK_MATCH: 'BANK_MATCH',
  MANUAL: 'MANUAL',
  BANK_IMPORT: 'BANK_IMPORT',
  INVENTORY: 'INVENTORY',
  ADJUSTMENT: 'ADJUSTMENT',
} as const;

export const MATCH_SUGGESTION_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  AUTO_POSTED: 'AUTO_POSTED',
} as const;
