/** Profile lifecycle — discovery never blocks app usage. */
export const BUSINESS_DISCOVERY_STATUS = {
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
} as const;

export type BusinessDiscoveryStatus =
  (typeof BUSINESS_DISCOVERY_STATUS)[keyof typeof BUSINESS_DISCOVERY_STATUS];

/** Active onboarding buckets (Prompt 13). */
export const DISCOVERY_BUCKET = {
  BUSINESS_IDENTITY: 'BUSINESS_IDENTITY',
  ORGANIZATION_STRUCTURE: 'ORGANIZATION_STRUCTURE',
  MANAGER_DISCOVERY: 'MANAGER_DISCOVERY',
  WORKFORCE_DISCOVERY: 'WORKFORCE_DISCOVERY',
  INVENTORY_DISCOVERY: 'INVENTORY_DISCOVERY',
  VENDOR_DISCOVERY: 'VENDOR_DISCOVERY',
  /** @deprecated Use ORGANIZATION_STRUCTURE — kept for bucket_data compat */
  ORGANIZATION: 'ORGANIZATION',
  /** @deprecated Use INVENTORY_DISCOVERY */
  INVENTORY: 'INVENTORY',
  /** @deprecated Use VENDOR_DISCOVERY */
  VENDORS: 'VENDORS',
} as const;

export type DiscoveryBucket =
  (typeof DISCOVERY_BUCKET)[keyof typeof DISCOVERY_BUCKET];

export type ActiveDiscoveryBucket =
  | typeof DISCOVERY_BUCKET.BUSINESS_IDENTITY
  | typeof DISCOVERY_BUCKET.ORGANIZATION_STRUCTURE
  | typeof DISCOVERY_BUCKET.MANAGER_DISCOVERY
  | typeof DISCOVERY_BUCKET.WORKFORCE_DISCOVERY
  | typeof DISCOVERY_BUCKET.INVENTORY_DISCOVERY
  | typeof DISCOVERY_BUCKET.VENDOR_DISCOVERY;

export const ACTIVE_DISCOVERY_BUCKET_ORDER: ActiveDiscoveryBucket[] = [
  DISCOVERY_BUCKET.BUSINESS_IDENTITY,
  DISCOVERY_BUCKET.ORGANIZATION_STRUCTURE,
  DISCOVERY_BUCKET.MANAGER_DISCOVERY,
  DISCOVERY_BUCKET.WORKFORCE_DISCOVERY,
  DISCOVERY_BUCKET.INVENTORY_DISCOVERY,
  DISCOVERY_BUCKET.VENDOR_DISCOVERY,
];

/** Legacy 4-bucket order — tests and old reports may reference this. */
export const DISCOVERY_BUCKET_ORDER: DiscoveryBucket[] =
  ACTIVE_DISCOVERY_BUCKET_ORDER;

export const DISCOVERY_BUCKET_LABELS: Record<ActiveDiscoveryBucket, string> = {
  BUSINESS_IDENTITY: 'Business Identity',
  ORGANIZATION_STRUCTURE: 'Organization Structure',
  MANAGER_DISCOVERY: 'Managers',
  WORKFORCE_DISCOVERY: 'Workforce',
  INVENTORY_DISCOVERY: 'Inventory',
  VENDOR_DISCOVERY: 'Vendors',
};

const LEGACY_BUCKET_MAP: Record<string, ActiveDiscoveryBucket> = {
  [DISCOVERY_BUCKET.ORGANIZATION]: DISCOVERY_BUCKET.ORGANIZATION_STRUCTURE,
  [DISCOVERY_BUCKET.INVENTORY]: DISCOVERY_BUCKET.INVENTORY_DISCOVERY,
  [DISCOVERY_BUCKET.VENDORS]: DISCOVERY_BUCKET.VENDOR_DISCOVERY,
};

export function normalizeDiscoveryBucket(
  bucket: string,
): ActiveDiscoveryBucket | null {
  if (
    (ACTIVE_DISCOVERY_BUCKET_ORDER as string[]).includes(bucket)
  ) {
    return bucket as ActiveDiscoveryBucket;
  }
  return LEGACY_BUCKET_MAP[bucket] ?? null;
}

export const FUTURE_DISCOVERY_BUCKETS = [
  'BOOKKEEPING',
  'LEDGER',
  'BANKING',
] as const;

/** Reminder schedule (hours). */
export const DISCOVERY_REMINDER_HOURS = {
  FIRST: 24,
  FINAL: 24 * 7,
} as const;

export const DISCOVERY_REMINDER_STAGE = {
  NONE: 0,
  FIRST_SENT: 1,
  FINAL_SENT: 2,
  PAUSED: 3,
} as const;

/** Document type → bucket contribution (reuse existing document registry). */
export const DOCUMENT_DISCOVERY_BUCKET_MAP: Record<string, ActiveDiscoveryBucket> = {
  PURCHASE_INVOICE: DISCOVERY_BUCKET.VENDOR_DISCOVERY,
  GOODS_RECEIPT: DISCOVERY_BUCKET.VENDOR_DISCOVERY,
  INVENTORY_IMPORT: DISCOVERY_BUCKET.INVENTORY_DISCOVERY,
  STOCK_REGISTER: DISCOVERY_BUCKET.INVENTORY_DISCOVERY,
};

/** Suggestion types that contribute to buckets when executed. */
export const SUGGESTION_DISCOVERY_BUCKET_MAP: Record<string, ActiveDiscoveryBucket> = {
  INITIAL_INVENTORY_IMPORT: DISCOVERY_BUCKET.INVENTORY_DISCOVERY,
  NEW_INVENTORY_ITEM: DISCOVERY_BUCKET.INVENTORY_DISCOVERY,
  CREATE_VENDOR: DISCOVERY_BUCKET.VENDOR_DISCOVERY,
};

export const BUSINESS_DISCOVERY_WORKFLOW_COMMAND = '/business_discovery';
